# Project information
site_name: Jay Oswald Blog
site_url: https://jay-oswald.github.io/blog
site_author: Jay Oswald
site_description: Mainly answers to various common questions on various Facebook groups

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins: []
